<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Persistence\Repositories\**" />
    <EmbeddedResource Remove="Persistence\Repositories\**" />
    <None Remove="Persistence\Repositories\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Persistence\Repositories\Repository.cs" />
    <Compile Include="Persistence\Repositories\RoleRepository.cs" />
    <Compile Include="Persistence\Repositories\UserRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcommerceAPI.Application\EcommerceAPI.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
